use_frameworks!

target 'engagelive_Example' do
  pod 'engagelive', :path => '../'

  target 'engagelive_Tests' do
    inherit! :search_paths
    pod 'AASegmentedControl'
    pod 'Socket.IO-Client-Swift', '~> 13.2.0'
    
  end
end
